### ISSUE TITLE
Need to repeatedly call MesonInit for "jump-to-file" to work properly

### ISSUE THREAD

**Issue by phako** [igankevich/mesonic#1]
For some reason I need to call :MesonInit before every :make call, otherwise, if the error happens in file that was not opened before through a compile issue, it will try to open "../some/path" instead of "some/path".

Meson is 0.40.1, vim is neovim 0.1.7

**Comment by igankevich** [comment]
As far as I remember, this may happen, if you try to open meson.build file using special '.' and '..' files (vim ../meson.build or :edit../meson.build inside vim). Do you open files like this?

**Comment by igankevich** [comment]
And do you have errors in meson.build file or ordinary source files?

**Comment by phako** [comment]
No, I only open one source file then compile and get an error in that file. No meson files open or having errors

**Comment by igankevich** [comment]
OK. I will try to test plugin with your neovim and meson version and see what happens.

**Comment by phako** [comment]
acutally, it seems that vala plays a role here

**Comment by igankevich** [comment]
OK. I tracked down the issue. I assume you use [this vala plugin](https://github.com/arrufat/vala.vim). If this is the case, then this plugin overwrites `errorformat` variable upon opening every vala source file, which is needed for mesonic to correctly open the file where compiler error occurred. The right place to set this variable is in [compiler plugin](http://vimdoc.sourceforge.net/htmldoc/usr_41.html#write-compiler-plugin), not in the ftdetect plugin.

I added vala error format string to mesonic. If you still want to use vala plugin for syntax highlighting, you can do something like this in your vimrc as a workaround:
```vim
call plug#begin(...)
...
Plug 'arrufat/vala.vim', {'do': 'rm ftdetect/vala.vim'}
...
call plug#end()
...
augroup vala
	autocmd!
	autocmd BufRead,BufNewFile *.vala,*.vapi,*.valadoc setfiletype vala
augroup END

```

**Comment by phako** [comment]
No, not that plugin, but an older, simpler version from the GNOME Wiki. It does exactly the same as you describe. Thanks you very much for you analysis, I'm completely lost when it comes tovim script

Will adapt your suggestion :)

**Comment by igankevich** [comment]
Glad it helped :-) I will close the issue now. Feel free to open another one if you have problems.
