### ISSUE TITLE
Redefinition of s:shiftwidth() every time a meson file is loaded. 

### ISSUE THREAD

**Issue by annacrombie** [igankevich/mesonic#10]
I'm using neovim and [vim-plug](https://github.com/junegunn/vim-plug).  The first time I load a meson.build file (or any meson file) everything works fine.  Each subsequent load of a meson file results in this error:
```
Error detected while processing ~/.config/nvim/plugged/mesonic/indent/meson.vim:
line   20:
E122: Function <SNR>55_shiftwidth already exists, add ! to replace it
```
It would seem that vim-plug is loading `indent/meson.vim` each time I open a meson file, and the referenced function is redefined each time as well.  None of my other plugins are giving me a similar issue, so I feel like vim-plug's behavior is ok in this case.  I solved it by doing as the error suggests and using `func!` instead of `func`.

**Comment by igankevich** [comment]
Looks like neovim issue to me, because I've never saw this error with ordinary vim. How a function which has script scope can be redefined in another script or by running the same script again?

Nevertheless, I will accept you pull request to be compatible with neovim. Thanks!
