### ISSUE TITLE
Enhance :MesonRun with cwd and arguments

### ISSUE THREAD

**Issue by Sahnvour** [igankevich/mesonic#16]
Hello, and thanks for this plugin that looks very handy.

I'd like to request a small enhancement to be able to specify:
- Where to run the targets with `:MesonRun`, if I understand correctly they are currently launched from the root build folder.
  Ideally both globally and on a per-target basis, or at least have a switch to run them from their current build folder.
- Arguments for "short" targets that are defined in subdirs.
  For example if a target `bar` is defined in subdir `foo`, I can run it with `:MesonRun bar` but `:MesonRun bar --some --args` will fail whereas `:MesonRun foo/bar --some --args` will succeed.

**Comment by igankevich** [comment]
Hello, Sahnvour! I will look into it when I have time. This code was contributed by @albfan and I don't know if it would be difficult to change or not :-)

**Comment by albfan** [comment]
I can take a look

**Comment by albfan** [comment]
That PR #17 should fix it

**Comment by Sahnvour** [comment]
Thanks ! Just tested it on my use case and can confirm it works.

What do you both think about my first bullet point ?
> Where to run the targets with :MesonRun, if I understand correctly they are currently launched from the root build folder.
Ideally both globally and on a per-target basis, or at least have a switch to run them from their current build folder.

I'm not sure how to make this convenient, but I have targets that are expected to run in specified locations (because of accompanying data), or at least in their `meson.current_build_dir()`.

**Comment by albfan** [comment]
Probably expose an example that needs this will show why it is inconvenient, in general an app which resources depends on its location is wrong.

You never move to /usr/bin to run anything, all is explicitly set.

This is a common problem for autotools and similar.

**Comment by Sahnvour** [comment]
I have executables (targets but also tests) that need to find resources. These resources are expected to be referenced in the current working directory of the executables. In Meson, I'm able to setup my build dir content so that the resources are there and found by the executables.
This is not the same thing as doing an install, because it also impacts tests, which should not be installed ; also installation is an additional step I'd like to avoid in this case.
With this setup I can keep my code simpler and safer : always expect resources to be there, no matter the configuration.

**Comment by albfan** [comment]
Meson provides ways so you can find your sources to run test

See source_root usage to find files not installed in glade tests:

https://gitlab.gnome.org/GNOME/glade/-/blob/master/meson.build#L72
https://gitlab.gnome.org/GNOME/glade/-/blob/master/tests/meson.build#L3

Don't let anything to depend on the directory app is. You never needed to move to /usr/bin to run any of your commands

**Comment by igankevich** [comment]
> have a switch to run them from their current build folder

If I understand you correctly, you want a `run_target` to be run from some specific directory. Meson by default does not do that: ["the command is run from an unspecified directory"](https://mesonbuild.com/Reference-manual_functions.html#run_target). If you want this behavior, you can write a script that uses `MESON_SUBDIR` to change directory and use this secipt it as a target. I don't think it is a good idea to modify Meson defaults with the plugin.

**Comment by Sahnvour** [comment]
You're right about `run_target`, I misremembered.
However [tests have a `workdir` argument](https://mesonbuild.com/Reference-manual_functions.html#test) so we could say supporting it and running tests in their workdir would be following the default Meson behavior.

**Comment by albfan** [comment]
But that is to set a directory where any result will be read, write, not to find the executable sources.

```
meson init
```

```
project('meson-c', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('meson_c', 'meson_c.c',
  install : true)

test('basic', exe)
```

I modify test to be:

```
test('basic', exe, workdir: meson.source_root())
```

and output is:

```
[
  {
    "cmd": [
      "/home/alberto/tutorial/meson-c/build/meson_c"
    ],
    "env": {},
    "name": "basic",
    "workdir": "/home/alberto/tutorial/meson-c",
    "timeout": 30,
    "suite": [
      "meson-c"
    ],
    "is_parallel": true,
    "priority": 0,
    "protocol": "exitcode",
    "depends": [
      "meson_c@exe"
    ]
  }
]
```

Anyway test is something runned from `:make test`

```
ninja: Entering directory `/home/alberto/tutorial/meson-c/build'
ninja: no work to do.
1/1 basic        OK              0.00s


Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/alberto/tutorial/meson-c/build/meson-logs/testlog.txt
```

Looks `:meson test basic` is not filtering to run only that test. If a `:MesonRunTest` is implemented that `workdir` should be take into account, but no for targets

**Comment by igankevich** [comment]
> However tests have a workdir argument so we could say supporting it and running tests in their workdir would be following the default Meson behavior.

Then we need a separate command (e.g. `:MesonTest`) to wrap `meson test` calls. As albfan said meson test will change working directory automatically in this case.

**Comment by igankevich** [comment]
I created new issue #19. We can continue our discussion there.
