### ISSUE TITLE
errorformat doubles in length each time `compiler meson` is executed

### ISSUE THREAD

**Issue by tbodt** [igankevich/mesonic#2]
To reproduce, open vim and run `compiler meson` repeatedly. Vim will run out of memory and crash before you can run it 20 times.

This is a big problem because it runs `compiler meson` every time you open a C file. It's annoying to have to restart vim after opening 17 files.

**Comment by igankevich** [comment]
I've never ran into this problem myself, but I'll look into it when I have time.

**Comment by igankevich** [comment]
I fixed the problem. Please, update the plugin to the latest version to see if it works with your vim configuration.
