### ISSUE TITLE
feature request: MesonConfigure without any options shows current configuration

### ISSUE THREAD

**Issue by bartlibert** [igankevich/mesonic#8]
It would be nice if "MesonConfigure" without any options would show the current configuration (maybe just the stdout output?).
If this is not possible, no problem, it would just be easy to be able to see the current configuration from vim instead of having to leave it to go to the terminal.

**Comment by igankevich** [comment]
This should be fairly easy. I will try to add it when I have more time for vim plugins :-)

**Comment by igankevich** [comment]
Now `MesonConfigure` can be called without arguments to show all options.

**Comment by bartlibert** [comment]
Great, thanks!
